### ISSUE TITLE
麻烦能把这个维护下吗

### ISSUE THREAD

**Issue by weitemi** [githoniel/node-ffi-generator-online#1]
麻烦能把这个维护下吗，我在window上Ubuntu系统中搭建了，在执行总是提示这个
![image](https://user-images.githubusercontent.com/7875391/49986569-52e48a80-ffab-11e8-80bf-2bc25c4233d6.png)
谢谢了

**Comment by githoniel** [comment]
请搭建在centos中，wsl不一定可以， ubuntu我也没玩过这个

**Comment by weitemi** [comment]
> 请搭建在centos中，wsl不一定可以， ubuntu我也没玩过这个
好吧，只能搭个centos了

**Comment by yh4922** [comment]
@weitemi 我是在centos 中搭建的 
在安装  yarn global add libclang 这个的时候报错了 
`make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/usr/local/share/.config/yarn/global/node_modules/ref/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-1127.el7.x86_64
gyp ERR! command "/root/.nvm/versions/node/v12.18.0/bin/node" "/root/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/share/.config/yarn/global/node_modules/ref
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok`
